# Generated by Django 4.2.6 on 2023-12-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('taskDescription', models.TextField()),
                ('is_completed', models.CharField(max_length=1)),
                ('Task_Assign_Date', models.DateField()),
            ],
        ),
    ]
