# Generated by Django 4.2.6 on 2023-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodels',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
